#!/usr/local/bin/perl

ifeq ($(MTK_EMMC_SUPPORT),yes)
BOARD_SECROIMAGE_PARTITION_SIZE:=5M
BOARD_SYSTEMIMAGE_PARTITION_SIZE:=529M
BOARD_CACHEIMAGE_PARTITION_SIZE:=160M
BOARD_USERDATAIMAGE_PARTITION_SIZE:=1039M
BOARD_FATIMAGE_PARTITION_SIZE:=0M
endif 
